### ISSUE TITLE
Debugger throws errors when it cleans up

### ISSUE THREAD

**Issue by hanssl** [Vector35/deprecated_python_debugger#121] opened 2021-01-11 22:21 UTC
Steps to reproduce:
1. Run the examples/md5_opc_freq.py file against /testbins/md5/md5_x64-linux
2. Observe the errors that occur after the status are printed.

![Screenshot from 2021-01-11 15-19-35](https://user-images.githubusercontent.com/649957/104244974-b5294700-5420-11eb-8555-f726e43b47fb.png)

**Comment by lwerdna** [comment] 2021-03-24 15:38
Thanks for the report. It looks like the exceptions are on the API side of things: `binaryninja/function.py`, `binaryninja/binaryview.py`, `binaryninja/filemetadata.py` and it's likely they've been resolved in a binaryninja released since this issue.

I've tried 2.3.2660 (Feb 24th):

```
>>> import binaryninja
>>> binaryninja.core_version()
'2.3.2660'
```

and could not reproduce the issue:

```
andrewl@ubuntu:~/repos/vector35/debugger/testbins/md5$ ./md5_opc_freq.py ../testbins/md5/md5_x64-linux
instr:     mov total:2294 percentage:50.15%
instr:     add total:967 percentage:21.14%
instr:     cmp total:255 percentage:5.57%
instr:      jb total:250 percentage:5.47%
instr:   movzx total:192 percentage:4.20%
instr:      or total:96 percentage:2.10%
instr:     and total:68 percentage:1.49%
instr:     lea total:61 percentage:1.33%
instr:     sub total:56 percentage:1.22%
instr:     shl total:54 percentage:1.18%
instr:     xor total:52 percentage:1.14%
instr:     not total:48 percentage:1.05%
instr:     rol total:44 percentage:0.96%
instr:     shr total:25 percentage:0.55%
instr:     ror total:20 percentage:0.44%
instr:     nop total:15 percentage:0.33%
instr:    retn total:15 percentage:0.33%
instr:    call total:14 percentage:0.31%
instr:    push total:14 percentage:0.31%
instr:     jmp total:12 percentage:0.26%
instr:     pop total:10 percentage:0.22%
instr:   leave total:5 percentage:0.11%
instr:     jae total:3 percentage:0.07%
instr:      ja total:2 percentage:0.04%
instr:      je total:2 percentage:0.04%
returned from MD5Final(), 4574 instructions
mov     : 2294 (50.2%)
add     : 967 (21.1%)
cmp     : 255 (5.6%)
jb      : 250 (5.5%)
movzx   : 192 (4.2%)
or      : 96 (2.1%)
and     : 68 (1.5%)
lea     : 61 (1.3%)
sub     : 56 (1.2%)
shl     : 54 (1.2%)
xor     : 52 (1.1%)
not     : 48 (1.0%)
rol     : 44 (1.0%)
shr     : 25 (0.5%)
ror     : 20 (0.4%)
nop     : 15 (0.3%)
retn    : 15 (0.3%)
call    : 14 (0.3%)
push    : 14 (0.3%)
jmp     : 12 (0.3%)
pop     : 10 (0.2%)
leave   : 5 (0.1%)
jae     : 3 (0.1%)
ja      : 2 (0.0%)
je      : 2 (0.0%)
MD5 ("abcdefghijklmnopqrstuvwxyz") = c3fcd3d76192e4007dfb496cca67e13b

Child exited with status 0
andrewl@ubuntu:~/repos/vector35/debugger/examples$ 
```

If you're still experiencing the issue, please reopen this with additional information.

**Closed as completed by lwerdna** 2021-03-24 15:38 UTC
